create table public.user_media_interactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  media_type text not null constraint user_media_interactions_media_type_check
    check (media_type in ('movie', 'tv')),
  media_id bigint not null constraint user_media_interactions_media_id_check
    check (media_id > 0),
  action text not null constraint user_media_interactions_action_check
    check (length(btrim(action)) > 0),
  rating numeric(3, 1) constraint user_media_interactions_rating_check
    check (rating is null or rating between 0 and 10),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_media_interactions_user_media_action_key
    unique (user_id, media_type, media_id, action)
);

create index user_media_interactions_user_action_idx
  on public.user_media_interactions (user_id, action, media_type);

create function public.set_user_media_interactions_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_user_media_interactions_updated_at
before update on public.user_media_interactions
for each row execute function public.set_user_media_interactions_updated_at();

revoke all on function public.set_user_media_interactions_updated_at() from public, anon, authenticated;

alter table public.user_media_interactions enable row level security;

create policy "Users can read their own media interactions"
on public.user_media_interactions for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert their own media interactions"
on public.user_media_interactions for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own media interactions"
on public.user_media_interactions for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own media interactions"
on public.user_media_interactions for delete
to authenticated
using ((select auth.uid()) = user_id);

grant select, insert, update, delete on table public.user_media_interactions to authenticated;
grant select, insert, update, delete on table public.user_media_interactions to service_role;
grant usage, select on sequence public.user_media_interactions_id_seq to authenticated, service_role;

insert into public.user_media_interactions (user_id, media_type, media_id, action, rating)
select distinct on (user_id, movie_id, action)
  user_id,
  'movie',
  movie_id,
  action,
  rating
from public.user_movie_interactions
where movie_id > 0 and length(btrim(action)) > 0
order by user_id, movie_id, action
on conflict (user_id, media_type, media_id, action) do nothing;

comment on table public.user_media_interactions is
  'Media-aware user interactions. user_movie_interactions is retained temporarily for rollback.';
